"""Add teacher column to Student

Revision ID: 7dd3206aca02
Revises: 6192dcd8903e
Create Date: 2025-06-09 13:38:44.469668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd3206aca02'
down_revision = '6192dcd8903e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.String(length=100), nullable=True))
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###
